import java.io.File;
import java.io.IOException;

import qualify.TestCase;

public class Test6 extends MotherTest {

	public void run() {
		// An exception is thrown here:
		int i = 'exception raised during run'
		check(b)
		System.out.println("I'm in the script 3");
	}

}